fix(*): fix on-pull-request workflow syntax

diff --git a/.github/workflows/on-pull-request-to-main-create.yaml b/.github/workflows/on-pull-request-to-main-create.yaml
--- a/.github/workflows/on-pull-request-to-main-create.yaml
+++ b/.github/workflows/on-pull-request-to-main-create.yaml
@@ -23,35 +23,35 @@ jobs:
         uses: actions/checkout@v2
 
       # Retrieves the Terraform CLI used in the GitHub action workflow
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+      #- name: Setup Terraform
+      #  uses: hashicorp/setup-terraform@v1
+      # with:
+      #    cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-      # Checks whether the repository has been properly formatted.
-      # If it isn't properly formatted this step will produce an error.
-      - name: Terraform Format
-        id: fmt
-        run: terraform fmt -check
+      ## Checks whether the repository has been properly formatted.
+      ## If it isn't properly formatted this step will produce an error.
+      #- name: Terraform Format
+      #  id: fmt
+      #  run: terraform fmt -check
 
-      # Initializes Terraform configurations.
-      - name: Terraform Init
-        id: init
-        run: terraform init
+      ## Initializes Terraform configurations.
+      #- name: Terraform Init
+      #  id: init
+      #  run: terraform init
 
-      # Validates Terraform configurations.
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+      ## Validates Terraform configurations.
+      #- name: Terraform Validate
+      #  id: validate
+      #  run: terraform validate -no-color
 
-      # Generates a Terraform plan.
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan -no-color
-        continue-on-error: true
+      ## Generates a Terraform plan.
+      #- name: Terraform Plan
+      #  id: plan
+      #  run: terraform plan -no-color
+      #  continue-on-error: true
 
-      # Adds a comment to the pull request with the results of the format, init and plan steps.
-      - name: Update Pull Request
+      ## Adds a comment to the pull request with the results of the format, init and plan steps.
+      #- name: Update Pull Request
         uses: actions/github-script@0.9.0
         env:
           PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
@@ -80,7 +80,7 @@ jobs:
               body: output
             })
 
-      # Returns whether a plan was successfully generated or not.
-      - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+      ## Returns whether a plan was successfully generated or not.
+      #- name: Terraform Plan Status
+      #if: steps.plan.outcome == 'failure'
+      #run: exit 1
